version: '3.8'

services:
  nest-api:
    container_name: nest-board
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app/

  nest-board-db:
    container_name: nest-db
    image: library/postgres:14.4-alpine
    ports:
      - "5332:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=nest
      - POSTGRES_PASSWORD=nest
      - POSTGRES_DB=nest